on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  build-head:
    name: 'Build'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5.7, 2.6.9, 2.7.5]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build
      run: |
          gem install bundler -v '2.2.21'
          bundle install
    - name: test
      run: 
          bundle exec rake test:local
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
