on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  build-head:
    name: 'Build head'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.7
    - name: Build
      run: |
          gem install bundler -v '2.2.21'
          bundle install
    - name: test
      run: 
          bundle exec rake test:local
    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: coverage/.resultset.json
    
    
        
  sonarcloud:
    needs: build-head
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: head-result
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: coverage/.resultset.json
        
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
